/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package literaldogwaterlibrary;

public class Library
{
    public boolean someLibraryMethod()
    {
        return true;
    }

    public String test()
    {
        return "kekw";
    }

    public static boolean isOdd(int number)
    {
        switch (number % 2)
        {
            case 0:
                return false;
            default:
                return true;
        }
    }
}
