/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package literaldogwaterlibrary;

import com.maximizer02.ldwl.*;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        LdwlBool bool = new LdwlBool();
        //double[] array = new double[]{213,123,123,4434,54,67,78,0,89,23,1,3,5678,2,34};
        //double[] array = new double[]{213,123,123,4434,54,67,78,0};
        //double[] result = misc.sortArray(array);
        System.out.println(bool.isTrue(1==1));
    }
}
