/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package literaldogwaterlibrary;

import com.maximizer02.ldwl.LdwlBool;
import com.maximizer02.ldwl.LdwlCore;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        LdwlCore classUnderTest = new LdwlCore();
        LdwlBool bool = new LdwlBool();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
        System.out.println(bool.isOdd(7));
    }
}
