/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package literaldogwaterlibrary;

import com.maximizer02.ldl.Core;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Core classUnderTest = new Core();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
        System.out.println(classUnderTest.isOdd(7));
    }
}
