/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maximizer02.ldwl;

public class LdwlCore
{
    public boolean someLibraryMethod()
    {
        return true;
    }

    public String test()
    {
        return "working";
    }

    public boolean isOdd(int number)
    {
        switch (number % 2)
        {
            case 0:
                return false;
            default:
                return true;
        }
    }
}
